### PR TITLE
Build docker image in GitHub Action

### PR DESCRIPTION
**Pull request by PlugFox**
Build and push amd64 and arm64 images in github

### CODE REVIEW

**Comment by PlugFox** [comment]
image

**Comment by PlugFox** [comment]
image

**Comment by Lulalaby** [comment]
Thanks for your contribution.

I do have some other way in mind tho to publish an official docker image more automated than that.

**Comment by PlugFox** [comment]
> Imma keep that open tho and point it later to the dev branch.

Main reason of my contribution is a `arm` image)
Because arm machines are slightly cheaper to rent.

**Comment by Lulalaby** [comment]
Yeah im aware. Im trying to figure out who's owning the tedicross org rn

**Pull request merged**
