### PR TITLE
Add dockerfile for running TediCross using docker

### PR DESCRIPTION
**Pull request by n1rna**
I also edited the readme file

### CODE REVIEW

**Comment by trgwii** [comment]
Tested?

**Comment by nima7r** [comment]
Yes, I tested this on an ubuntu machine and had no problems with it.

**Comment by trgwii** [comment]
Alright, I'll test on a Windows host tomorrow and merge if all goes well

**Comment by Suppen** [comment]
An official Dockerfile and Dockerimage has been released. Closing this PR without merging

**Pull request closed without merging**
