### PR TITLE
Added three new optional helpers for discord2telegram

### PR DESCRIPTION
**Pull request by jers1k**
Reworked the way new helpers processed discord2telegram messages:

01. Removed removeNewlineSpaces helper and included check for whitespace following custom emoji to removeCustomEmojis helper instead.
02. Reworked filterCustomEmojis helper. It takes a string and has three states - default, remove and replace:
    * `default` - custom emojis will be transferred without any processing (ex: <:emojisnhead:1102667149627113602> My Text);
    * `remove` - custom emojis will be removed from the output (ex: My Text);
    * `replace` - custom emojis will be replaced with a definable string. Defined in `replaceCustomEmojisWith` (ex: 🔹 My Text).
03. Made all new helpers to be optional. 
04. Disabled all new helpers by default.
05. Cleanded up md2html.ts - doing nothing there in this version.
06. Updated README.md

### CODE REVIEW

**Comment by Jers1k** [comment]
Now, this one should be much easier to like. Let me know!

**Comment by Lulalaby** [comment]
Target dev please in future, merge conflicts now :)

**Comment by Jers1k** [comment]
@Lulalaby good point. Just resolved the conflicts

**Comment by Lulalaby** [comment]
I think u forgot to push

**Comment by Solomag** [comment]
So, how can I embed this line in settings? Need to add it in this format? @Jers1k 

```
telegram:
   token:   `tokennumber` 
...
...
...
   filterCustomEmojis:   replace
   replaceCustomEmojisWith:   default
discord:
...
```

**Comment by jers1k** [comment]
"

> So, how can I embed this line in settings? Need to add it in this format? @Jers1k
> 
> ```
> telegram:
>    token:   `tokennumber` 
> ...
> ...
> ...
>    filterCustomEmojis:   replace
>    replaceCustomEmojisWith:   default
> discord:
> ...
> ```

That's correct. Here's an example: 
```telegram:
  ...
  sendEmojiWithStickers: true
  filterCustomEmojis: 'default'
  replaceCustomEmojisWith: '🔹'
  replaceAtSign: false
  replaceAtSignWith: '#'
  removeExcessiveSpacings: false

**Comment by Solomag** [comment]
I tried to add these lines (everything, so as not to confuse anything). After starting the program, the text file was automatically updated, as a result, the structure of the settings changed outwardly, and the lines disappeared.

It began to look like this:
notepad++_aTvPebv21S

**Comment by jers1k** [comment]
@Solomag I just tested and it seems to work fine on my end. Are you sure you're on dev branch? Because I don't think it was merged to master yet.

**Comment by Solomag** [comment]
It is likely that these lines are already in the readme of the project. I'll try to check later.

**Pull request merged**
