### PR TITLE
Refactored classes to typescript

### PR DESCRIPTION
**Pull request by lexermal**
Hello, 
like we discussed some days ago, I refactored all JavaScript files to Typescript.

I think I applied the right data types. 
At functions using ramda I often was not able to determine the data type. These parts might need an additional look or possibly a refactoring to plain JavaScript.

I found some functions using private or officially not existing functions, which I refactored to new ones and added a TODO for validation or further steps to investigate.

After a short test with multiple Discord channels sending messages to Telegram, it worked as expected.

### CODE REVIEW

**Comment by trgwii** [comment]
LGTM, @Suppen can we run this tree in our main instance for a day or two?

**Comment by Suppen** [comment]
Currently put on a separate branch `ts-refactor`. The TediCross instance running in the support group is now using this code. Will merge to master if there are no issues

**Comment by Suppen** [comment]
This has now been merged into the develop branch, and will thus be included in the next version of TediCross

**Comment by Suppen** [comment]
I have fixed the code a bit. Made a separate `dist/` directory, instead of putting all the js files next to the ts files. Removed typings from jsdoc. The changes are available on the develop branch.
There's an insane amount of type issues if I make the linter more aggressive. Fixing up all that will take a lot of time. It is, however, to be expected when a project is migrated from JS to TS.
The code builds and runs in its current state.

**Pull request merged**
